# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa0745a0810a1e75e36a42c7dc4f33c591d6293efc7de0a89a2745ea0a97e68e036acbb9f88c8b267bcbdba9f59a9f63168188fa4e4425fb3db466f502249c14

test:
  secret_key_base: 80e0e1fc23e851af7a095d1c1dbc63726135687db5a10622677dc54c231e35f0309365382da65b61d9da44d80b81a20d9890cc728eedfe67f2db3be23ac08288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
